version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./models:/app/models
      - ./logs:/app/logs
      - ./temp:/app/temp
    environment:
      - DEBUG=true
      - ENABLE_DOCS=true
      - AUTO_CONFIG_GPU=false
    restart: unless-stopped

  # You can add frontend service here if needed
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend